services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/p360-hackaton-backend?schema=public
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
      target: migrations
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/p360-hackaton-backend?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: p360-hackaton-backend
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
